name = "Guild 2.0"
author = "Kaland"
version = "1.0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "01fa7b6b1e7f2a645a0d4a4e4edbc9c8a9ec5d52d2de79e74fffc2913a710ae5"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.249"
