name = "Guild 2.0"
author = "Kaland"
version = "1.0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "25f0ac502ffdd5a7401b11ed2f6feb664b41c0f4eb8a625a3eda503e427c691e"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.249"
