name = "Guild 2.0"
author = "Kaland"
version = "1.0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "8ad5950c04d55430b5352a7f8e46b4371ec6623dc1a5240c5633a76cf1712f15"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.249"
